export const Get_USER_WALLET_REQUEST = "Get_USER_WALLET_REQUEST"
export const Get_USER_WALLET_SUCCESS = "Get_USER_WALLET_SUCCESS"
export const Get_USER_WALLET_FAILURE = "Get_USER_WALLET_FAILURE"

export const Get_WALLET_TRANSACTION_REQUEST = "Get_WALLET_TRANSACTION_REQUEST"
export const Get_WALLET_TRANSACTION_SUCCESS = "Get_WALLET_TRANSACTION_SUCCESS"
export const Get_WALLET_TRANSACTION_FAILURE = "Get_WALLET_TRANSACTION_FAILURE"

export const DEPOSIT_MONEY_REQUEST = "DEPOSIT_MONEY_REQUEST"
export const DEPOSIT_MONEY_SUCCESS = "DEPOSIT_MONEY_SUCCESS"
export const DEPOSIT_MONEY_FAILURE = "DEPOSIT_MONEY_FAILURE"

export const TRANSFER_MONEY_REQUEST = "TRANSFER_MONEY_REQUEST"
export const TRANSFER_MONEY_SUCCESS = "TRANSFER_MONEY_SUCCESS"
export const TRANSFER_MONEY_FAILURE = "TRANSFER_MONEY_FAILURE"